matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
    - os: osx
      language: objective-c
      osx_image: xcode7.3.1
script:
  - swift build
  - swift test
before_install:
  - chmod ugo+x ./scripts/run-tests.sh
  - . ./scripts/run-tests.sh
notifications:
  email: true
